config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users, only: [:index, :show] do
    resources :items, only: [:create,:destroy]
  end

  root 'users#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @item = Item.new(item_params)
    @item.user = current_user

    if @item.save
      flash[:notice] = 'Item was saved.'
      redirect_to root_path
    else
      flash[:alert] = 'There was an error saving the item. Please try again.'
      redirect_to root_path
    end
  end

  def destroy
    @item = Item.destroy(params[:id])

    respond_to do |f|
      f.html { redirect_to root_path }
      f.js
    end

    # @item = Item.find(params[:id])

    # if @item.destroy
    #   flash[:notice] = 'Item was completed.'
    #   redirect_to root_path
    # else
    #   flash[:alert] = 'There was an error completing the item. Please try again.'
    #   redirect_to root_path
    # end
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if params[:id]
      @user = User.find(params[:id])
    else
      @user = current_user
    end
    @items = nil
    @items = @user.items if @user
    @item = Item.new
  end

  def index
    @users = User.all.select{ |u| u.items.any? }
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [@user, @item], html: {class:'pure-form'} do |f| %>
  <%= f.text_field :name, placeholder: "Enter a new task" %>
  <%= f.submit "Create", class: 'pure-button pure-button-primary' %>
<% end %>

app/views/items/_item.html.erb
<tr id="item<%= item.id %>">
  <% if current_user == @user %>
    <td class='center w-10'>
      <%= link_to user_item_path(@user,item), method: :delete, remote: true do %>
        <i class="fal fa-times"></i>
      <% end %>
    </td>
  <% end %>
  <% if item.created_at+7.days < Time.now %>
  <td class='center red w-20'>
    <small><%= distance_of_time_in_words(Time.now,item.created_at+7.days) + " overdue" %></small>
  </td>
  <% else %>
  <td class='center green w-20'>
    <small><%= distance_of_time_in_words(item.created_at,Time.now) + " ago" %></small>
  </td>
  <% end %>


  <td><%= item.name %></td>
</tr>

app/views/items/destroy.js.erb
$('#item<%= @item.id %>').remove();

app/views/layouts/_nav.html.erb
<% if current_user %>
  <li class="pure-menu-item">
    <%= link_to 'User Index', users_path %>
  </li>
  <li class="pure-menu-item">
    <%= link_to 'Edit Profile', edit_user_registration_path %>
  </li>
  <li class="pure-menu-item">
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
  </li>
  <li class="pure-menu-item">
    Signed in as <%= current_user.username %>
    <small><sub>
      <%= link_to "Not you?", destroy_user_session_path, method: :delete %>
    </sub></small>
  </li>
<% else %>
  <li class="pure-menu-item">
    <%= link_to 'Sign Up', new_user_registration_path %>
  </li>
  <li class="pure-menu-item">
    <%= link_to 'Sign In', new_user_session_path %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocitoff</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/base-min.css">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container pure-g">
      <div class="pure-menu pure-menu-horizontal pure-u-5-5">
        <%= link_to 'Blocitoff', root_path, class:'pure-menu-heading pure-menu-link' %>
        <ul class="pure-menu-list">
            <%= render '/layouts/nav' %>
        </ul>
      </div>




      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<div class='pure-u-5-5 center'>
  <h2>Users Trying to Complete Tasks</h2>
  <ul style='list-style:none;padding-left:0;'>
    <% @users.sort_by{|u|u.items.sort_by{|i|i.created_at}.first.created_at}[0..10].each do |user| %>
      <li><%= link_to user.username, user_path(user) %></li>
    <% end %>
  </ul>

</div>
<script>blocmetrics.report('user#index');</script>

app/views/users/show.html.erb
  <% if current_user %>

    <% if current_user == @user %>
      <div class='pure-u-5-5 center item-input'>
        <%= render partial: '/items/form', locals: {user: @user,item: @item} %>
      </div>
    <% end %>

    <div class='pure-u-5-5'>
      <table class='pure-table pure-table-horizontal list'>
        <tbody>
          <% if @items.any? %>
            <% @items.sort_by{|i|i.created_at}.each do |item| %>
              <%= render partial: '/items/item', locals: {item: item} %>
            <% end %>
          <% else %>
            <h5 class='center'>You have no tasks!</h5>
          <% end%>
        </tbody>
      </table>
    </div>

  <% else %>

    <div class='pure-u-5-5'>
      <h1 class='center'>Welcome to Blocitoff</h1>
    </div>
    <div class='pure-u-2-5'>
      <h3>What is Blocitoff?</h3>
    </div>
    <div class='pure-u-3-5'>
      <p>
        Blocitoff is an online to do list app with a twist. Instead of letting your items sit on your list forever when you inevitably forget to check them off, your items will expire 7 days after their creation. If you aren't going to do it within 7 days should it really be on your todo list?
      </p>
    </div>

    <div class='pure-u-5-5 center'>
      <%= link_to "Try it today!", new_user_registration_path, class:'pure-button pure-button-primary' %>
    </div>

  <% end %>
<script>blocmetrics.report('user#show');</script>

app/views/welcome/index.html.erb
<div class="pure-u-5-5">
  <h1 class='center'>Welcome to Blocitoff</h1>

</div>
<script>blocmetrics.report('welcome#index');</script>